### ISSUE TITLE
Relation to jrast/HSR-Latex-Package/beamer?

### ISSUE THREAD

**Issue by das-g** [HBadertscher/HSRPresentation#5]
What is this project's relation (if any) to [:octocat:`/jrast/HSR-Latex-Package`](https://github.com/jrast/HSR-Latex-Package)<code>/[beamer](https://github.com/jrast/HSR-Latex-Package/tree/master/beamer)</code>
 (beyond using color definition based on [`HSRColors.sty` from there](https://github.com/jrast/HSR-Latex-Package/blob/master/HSRColors.sty))?

Are there any ideas or features in :octocat:`/jrast/HSR-Latex-Package/beamer` that this project should adopt? Or was `HSRPresentation` already based on the latest revision of :octocat:`/jrast/HSR-Latex-Package/beamer` anyway?

---

Was ist die Beziehung (falls denn eine besteht) dieses Projekts zu [:octocat:`/jrast/HSR-Latex-Package`](https://github.com/jrast/HSR-Latex-Package)<code>/[beamer](https://github.com/jrast/HSR-Latex-Package/tree/master/beamer)</code> (ausser dass es auf dem [dortigen `HSRColors.sty`](https://github.com/jrast/HSR-Latex-Package/blob/master/HSRColors.sty) basierende Farbdefinitionen verwendet)?

Hat's in :octocat:`/jrast/HSR-Latex-Package/beamer` Ideen oder Featues, die dieses Projekt übernehmen sollte? Oder ist `HSRPresentation` sowieso bereits eine Weiterentwicklung von :octocat:`/jrast/HSR-Latex-Package/beamer`?

**Comment by HBadertscher** [comment]
This project (and also the closely related [`HSRReport`](https://github.com/HBadertscher/HSRReport) project for docs and theses at HSR) have no relation to the `HSR-Latex-Package` by jrast and are not based on these style files. The only exception is, as you noted, the `HSRcolors.sty` file, which is taken from [`/jrast/HSR-Latex-Package`](https://github.com/jrast/HSR-Latex-Package) and which I originally know from [`/HSR-Stud/header`](https://github.com/HSR-Stud/header/tree/header2.0).

I think the main difference between "my" two templates and jrast's is, he provides very simple and light-weight `.sty` files, which can be used for almost anything. These classes, especially [HSRReport](https://github.com/HBadertscher/HSRReport) are full "batteries-included" templates which should let anybody get something up and running very quickly. Thus, it already includes stuff like `amsmath` or `listings` which a user *might* probably need. And this is why I chose to create the headers as `.tex` and not as `.sty` files, as this allows the user to add / remove / change stuff.

**Comment by das-g** [comment]
Cool. Thanks for the info.
